### SHORTEN URL ROUTE
POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "url": "https://cloud.mongodb.com/v2/632b328c37519f138fdd3874#metrics/replicaSet/632b348beeb8063a3465d4dc/explorer/test/urls/find"
}

### HOME ROUTE
GET http://localhost:5000/